### ISSUE TITLE
Filed to deserialize response of type

### ISSUE THREAD

**Issue by rw-LukaszPrzybyla** [triforkams/geohash-facet#9]
When I try used:
<code>
        QueryBuilder queryBuilder = ...

```
    GeoFacetBuilder facetBuilder = new GeoFacetBuilder(TYPE_NAME).
                                                       field(FIELD_NAME).
                                                       factor(0.8).showGeohashCell(false);

    SearchResponse response = client.prepareSearch(INDEX_NAME)
            .setSearchType(SearchType.COUNT)
            .setQuery(queryBuilder)
            .addFacet(facetBuilder)
            .execute().actionGet();

    GeohashFacet geohashFacet = (GeohashFacet) response.getFacets().facetsAsMap().get(TYPE_NAME);
```

</code>
I had from prepareSearch: 
rg.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.search.SearchResponse]
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:148)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:125)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.AssertionError
    at org.elasticsearch.common.io.stream.StreamInput.readVLong(StreamInput.java:220)
    at org.elasticsearch.common.io.stream.AdapterStreamInput.readVLong(AdapterStreamInput.java:117)
    at nl.trifork.elasticsearch.facet.geohash.Cluster.readFrom(Cluster.java:112)
    at nl.trifork.elasticsearch.facet.geohash.InternalGeohashFacet.readFrom(InternalGeohashFacet.java:103)
    at nl.trifork.elasticsearch.facet.geohash.InternalGeohashFacet.readGeoClusterFacet(InternalGeohashFacet.java:89)
    at nl.trifork.elasticsearch.facet.geohash.InternalGeohashFacet$1.readFacet(InternalGeohashFacet.java:27)
    at org.elasticsearch.search.facet.InternalFacets.readFrom(InternalFacets.java:148)
    at org.elasticsearch.search.facet.InternalFacets.readFacets(InternalFacets.java:130)
    at org.elasticsearch.search.internal.InternalSearchResponse.readFrom(InternalSearchResponse.java:113)
    at org.elasticsearch.search.internal.InternalSearchResponse.readInternalSearchResponse(InternalSearchResponse.java:105)
    at org.elasticsearch.action.search.SearchResponse.readFrom(SearchResponse.java:230)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:146)
    ... 23 more

Same bug was in geocluster-facet? What I can do?

**Comment by ginaluca** [comment]
Hi,

it's definitely a bug in the plugin. While I investigate, you might switch to using the REST API instead of the java client.

  Gianluca

**Comment by rw-LukaszPrzybyla** [comment]
Hello. I know about Jest framework but was nice use this plugin if it is. Will be fix of this bug?

**Comment by rw-LukaszPrzybyla** [comment]
Issue was fixed.
